apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: dev
  labels:
    app: db
data:
  POSTGRES_DB: students
  POSTGRES_USER: postgres
  POSTGRES_LOGIN: postgres
  POSTGRES_PASSWORD: querty123
