apiVersion: v1
kind: Service
metadata:
  #name: postgres
  name: db
  namespace: dev
  labels:
    app: db
spec:
  #type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db