apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: dev-myapp
  labels:
    type: local
    app: db
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql