apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-secret
  namespace: dev
  labels:
    app: pgadmin
data:
  PGADMIN_DEFAULT_EMAIL: admin@google.com
  PGADMIN_DEFAULT_PASSWORD: pass123
  PGADMIN_PORT: 80
