apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: dev-myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: 'marcheol/my-app:1.0'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-secret
