apiVersion: v1
kind: ConfigMap
metadata:
  name: app-secret
  labels:
    app: my-app
data:
  POSTGRES_DB: students
  POSTGRES_USER: postgres
  POSTGRES_LOGIN: postgres
  POSTGRES_PASSWORD: querty123
