apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  type: NodePort
  ports:
    - port: 5000
#      targetPort: 5000
#      nodePort: 3000
  selector:
    app: my-app