apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: 'marcheol/my-app:1.0'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: app-secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "75m"
            limits:
              memory: "128Mi"
              cpu: "100m"
