apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: dev
  labels:
    app: my-app
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 5000
  selector:
    app: my-app